language: python
### currently only testing on python 2.7 and 3.5
python:
  - "2.7"
#  - "2.7"
#  - "3.2"
#  - "3.3"
#  - "3.4"
  - "3.5"
#  - "3.5-dev" # 3.5 development branch
#  - "3.6"
#  - "3.6-dev" # 3.6 development branch
#  - "3.7-dev" # 3.7 development branch
#  - "nightly" # currently points to 3.7-dev

### un-comment to turn off email notifications
#notifications:
#  email: false

### Setup anaconda
before_install:
  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  ### The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
### Install packages
install:
  - conda create --yes -n env_name python=$TRAVIS_PYTHON_VERSION pip numpy scipy pandas nose
  - source activate env_name
#  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy nose pandas
#  - python setup.py install
  - conda install pip
  - pip install SRC/python
### Run test
script:
   - nosetests SRC/python/gr50/tests/test.py

### using Anaconda install, so no need to install numpy, scipy
#install:
#  - pip install numpy
#  - pip install scipy
#  - pip install pandas
#  - pip install SRC/python/
#  - pip install -r requirements.txt
# command to run tests
#script: nosetests SRC/python/gr50/tests/test.py
