#' Simulated dose-response assay data (Case A)
#'
#' This is the dataset corresponding to Case A (example 1 in MATLAB scripts).
#' See this page for details of the different cases of input considered:
#' \url{https://github.com/sorgerlab/gr50_tools/blob/master/README.md}
#' The data was generated by the python script found here:
#' \url{https://github.com/sorgerlab/gr50_tools/blob/master/examples/generate_data/generate_data.py}
#'
#'
#' @format A data frame with 1008 rows and 9 variables:
#' \itemize{
#'   \item cell_line: the cell-line used (MCF10A, MCF7, BT20)
#'   \item agent: the drug used (drugA, drugB, drugC, drugD)
#'   \item pertubation: an example of another key variable (e.g different
#'   media, a co-treatment, etc.) (0, 1)
#'   \item replicate: replicate number, (1, 2, 3)
#'   \item time: time of assay measured in hours (48, 72)
#'   \item concentration: concentration of the perturbagen on which dose-response curves
#'    will be evaluated (not log transformed)
#'   \item cell_count: the measure of cell number (or a surrogate of cell number) after treatment at the end of the assay
#'   \item cell_count__ctrl: the measure of cell number in control
#'   (e.g. untreated or DMSO-treated) wells from the same plate at the end of the assay
#'   \item cell_count__time0: the measure of cell number in untreated wells grown in
#'    parallel until the time of treatment
#' }
#' @return An example dataset in the form of "Case A" generated for use with \code{\link{GRfit}}
#' @source \url{https://github.com/sorgerlab/gr50_tools/blob/master/INPUT/toy_example_input1.tsv}
"inputCaseA"

#' Simulated dose-response assay data (Case C)
#'
#' This is the dataset corresponding to Case C (example 4 in MATLAB scripts).
#' The dataset is equivalent to that of Case A, but in a different form.
#' See this page for details of the different cases of input considered:
#' \url{https://github.com/sorgerlab/gr50_tools/blob/master/README.md}
#' The data was generated by the python script found here:
#' \url{https://github.com/sorgerlab/gr50_tools/blob/master/examples/generate_data/generate_data.py}
#'
#'
#' @format A data frame with 1352 rows and 7 variables:
#' \itemize{
#'   \item cell_line: the cell-line used (MCF10A, MCF7, BT20)
#'   \item agent: the drug used (-, drugA, drugB, drugC, drugD)
#'   \item pertubation: an example of another key variable (e.g different
#'   media, a co-treatment, etc.) (0, 1)
#'   \item replicate: replicate number, (1, 2, 3)
#'   \item time: time of assay measured in hours (0, 48, 72)
#'   \item concentration: concentration of the perturbagen on which dose-response curves
#'    will be evaluated (not log transformed)
#'   \item cell_count: measure of cell number or a surrogate of the number of cells.
#' }
#' @return An example dataset in the form of "Case C" generated for use with \code{\link{GRfit}}
#' @source \url{https://github.com/sorgerlab/gr50_tools/blob/master/INPUT/toy_example_input4.tsv}
"inputCaseC"
