#' Dose-Response Curves
#'
#' This function plots the Growth-rate inhibition dose-response curves for a
#' given set of data.
#'
#' @param fitData an element of class GRfit, generated by the GRfit function.
#' @param experiments the names of the experiments to plot (or "all")
#' @param min the minimum concentration to plot (for curves)
#' @param max the maximum concentration to plot (for curves)
#' @param points a logical value indicating whether points (individual GR
#' values) will be plotted
#' @param curves a logical value indicating whether sigmoidal dose-response
#' curves will be plotted
#' @param plotly a logical value indicating whether to output a ggplot2 graph
#' or a ggplotly graph
#'
#' @return ggplot2 or ggplotly graphs of Growth-rate inhibition dose-response
#' curves
#' @author Nicholas Clark
#' @details
#' Given a SummarizedExperiment object created \code{\link{GRfit}},
#' this function plots these GR values (versus concentration) and/or the
#' sigmoidal curves fitted to the sets of points. The results can be viewed
#' in a static ggplot image or an interactive plotly graph.
#'
#' The "min" and "max" parameters control the concentration values for which
#' the curves are plotted. They are automatically set to the minimum and
#' maximum concentrations of the data, but can be set by the user as well.
#' "min" and "max" take raw values (not log transformed) for concentration.
#'
#' By default, curves and points are plotted for all experiments. To specify
#' a smaller set of experiments, use the "experiments" parameter. To see the
#' names of individual experiments, use
#' \code{GRfitObject$parameter_table$experiment}. See the examples below.
#' @seealso To create the object needed for this function, see
#' \code{\link{GRfit}}. For other visualizations, see \code{\link{GRbox}} and
#' \code{\link{GRscatter}}. For online GR calculator and browser, see
#' \url{http://www.grcalculator.org}.
#' @examples
#' # Load Case A (example 1) input
#' data("inputCaseA")
#' # Run GRfit function with case = "A"
#' drc_output = GRfit(inputCaseA,
#' groupingVariables = c('cell_line','agent'))
#' GRdrawDRC(drc_output, experiments = c('BT20 drugA', 'MCF10A drugA',
#' 'MCF7 drugA'), min = 10^(-4), max = 10^2)
#' GRdrawDRC(drc_output, plotly = FALSE)
#' @export

GRdrawDRC <- function(fitData, experiments = "all", min = "auto", max = "auto",
                      points = TRUE, curves = TRUE, plotly = TRUE) {
  if(points == FALSE & curves == FALSE) {
    stop('You must show either points or curves or both')
  }
  # declaring values NULL to avoid note on package check
  log10_concentration = NULL
  experiment = NULL
  data = S4Vectors::metadata(fitData)[[1]]
  parameterTable = cbind(as.data.frame(SummarizedExperiment::colData(fitData)),
                        t(SummarizedExperiment::assay(fitData)))
  groupingVariables = S4Vectors::metadata(fitData)[[2]]
  data$log10_concentration = log10(data$concentration)
  tmp<-data[,groupingVariables, drop = FALSE]
  experimentNew = (apply(tmp,1, function(x) (paste(x,collapse=" "))))
  if(length(groupingVariables) > 0) {
    data$experiment = as.factor(experimentNew)
  } else {
    data$experiment = as.factor("All Data")
  }
  if(!identical(experiments, "all")) {
    parameterTable = parameterTable[parameterTable$experiment %in%
                                      experiments, ]
    data = data[data$experiment %in% experiments, ]
  }
  exps = unique(parameterTable$experiment)
  if(min == "auto") {
    min_conc = min(data$concentration, na.rm = TRUE)
  } else {
    min_conc = min
  }
  if(max == "auto") {
    max_conc = max(data$concentration, na.rm = TRUE)
  } else {
    max_conc = max
  }
  len = (log10(max_conc) - log10(min_conc))*100
  Concentration = 10^(seq(log10(min_conc) - 1, log10(max_conc) + 1,
                          length.out = len))
  curve_data_all = NULL
  for(exp in exps) {
    row = which(parameterTable$experiment == exp)
    EC50 = parameterTable$GEC50[row]
    GRinf = parameterTable$GRinf[row]
    Hill = parameterTable$Hill[row]
    logistic_3u = function(c){GRinf + (1 - GRinf)/(1 + (c/EC50)^Hill)}
    curve_data = as.matrix(Concentration)
    colnames(curve_data) = "Concentration"
    if(parameterTable$fit[row] == "sigmoid") {
      GR = apply(curve_data, 1, logistic_3u)
    } else {
      GR = parameterTable$flat_fit[row]
    }
    curve_data = cbind(curve_data, GR)
    curve_data = as.data.frame(curve_data)
    curve_data$experiment = exp
    if(is.null(curve_data_all)){
      curve_data_all = curve_data
    } else {
      curve_data_all = rbind(curve_data_all, curve_data)
    }
  }
  curve_data_all$experiment = as.factor(curve_data_all$experiment)

  if(points == TRUE & curves == FALSE) {
    p = ggplot2::ggplot(data = data, ggplot2::aes(x = log10_concentration,
                        y = GR, colour = experiment)) + ggplot2::geom_point()
  } else if(points == FALSE & curves == TRUE) {
    p = ggplot2::ggplot(data = curve_data_all,
        ggplot2::aes(x = log10(Concentration),
                    y = GR, colour = experiment)) + ggplot2::geom_line()
  } else if(points == TRUE & curves == TRUE) {
    p = ggplot2::ggplot() + ggplot2::geom_line(data = curve_data_all,
                            ggplot2::aes(x = log10(Concentration), y = GR,
                                          colour = experiment)) +
      ggplot2::geom_point(data = data, ggplot2::aes(x = log10_concentration,
                          y = GR, colour = experiment))
  }
  p = p + ggplot2::coord_cartesian(xlim = c(log10(min_conc)-0.1,
                                            log10(max_conc)+0.1),
                                   ylim = c(-1, 1.5), expand = TRUE) +
    ggplot2::ggtitle("Concentration vs. GR values") +
    ggplot2::xlab('Concentration (log10 scale)') +
    ggplot2::ylab('GR value') + ggplot2::labs(colour = "") +
    ggplot2::geom_hline(yintercept = 1, size = .25) +
    ggplot2::geom_hline(yintercept = 0, size = .25) +
    ggplot2::geom_hline(yintercept = -1, size = .25)

  if(plotly == TRUE) {
    q = plotly::ggplotly(p)
    return(q)
  } else {
    return(p)
  }
}
